### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
# 2D
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3D
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange like range()
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [6]:
# with reshape
np.arange(16).reshape(2, 2, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
# np.ones
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# np.zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# np.random
np.random.random((3, 4))

array([[0.60565361, 0.07717371, 0.25174124, 0.88400135],
       [0.36841921, 0.05076834, 0.33598239, 0.05346177],
       [0.16339993, 0.95277175, 0.04378902, 0.01568139]])

In [10]:
# np.linspace
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [11]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [12]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3, 4)
# a2 = np.arange(12, dtype=float).reshape(3, 4, order='F')
a3 = np.arange(8).reshape(2, 2, 2)

a1, a2, a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [13]:
# ndim
a3.ndim

3

In [14]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
# itemsize
a3.itemsize

8

In [17]:
# dtype
print(a1.dtype, a1.itemsize)
print(a2.dtype, a2.itemsize)
print(a3.dtype, a3.itemsize)

int32 4
float64 8
int64 8


### Changing Datatype

In [18]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [19]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

a1, a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

#### Scalar operations(1D Array)

In [20]:
# arithmetic(+,-,*,/,//,%,**)
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
# relational(<,>,<=,>=,==,!=)
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

#### Vector operations(2D Array)

In [22]:
a1, a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [23]:
# arithmetic(+,-,*,/,//,%,**)

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [24]:
# relational(<,>,<=,>=,==,!=)
a1 <= a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Array Functions

In [25]:
a1 = np.random.random((3, 3))

In [26]:
a1

array([[0.06915695, 0.64351714, 0.71452513],
       [0.29704354, 0.86401685, 0.3880018 ],
       [0.25701268, 0.1955367 , 0.17760326]])

In [27]:
a2 = np.round(a1 * 100, 2)  # np.round is equivalent to np.around
a2

array([[ 6.92, 64.35, 71.45],
       [29.7 , 86.4 , 38.8 ],
       [25.7 , 19.55, 17.76]])

In [28]:
# max/min/sum/prod
# 0 -> col and 1 -> row in Numpy
np.max(a2, axis=0)

array([29.7 , 86.4 , 71.45])

In [29]:
# mean/median/std/var
np.mean(a2, axis=1)

array([47.57333333, 51.63333333, 21.00333333])

In [30]:
# trigonomoetric functions
np.sin(a2)

array([[ 0.59463749,  0.99861434,  0.72196017],
       [-0.98948708, -0.99998077,  0.89160987],
       [ 0.53732218,  0.64455727, -0.88642145]])

In [31]:
# dot product
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [32]:
# log and exp(exponents)
# e=2.71828
# exp => e^x
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [33]:
# round/floor/ceil
np.ceil(np.random.random((2, 3)) * 100)

array([[49., 73., 94.],
       [83., 72., 78.]])

### Indexing and Slicing

In [34]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

a1, a2, a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [35]:
print(a1[1])

1


In [36]:
print(a2[1, 0])

4


In [37]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
print(a3[1, 0, 1])

5


In [39]:
print(a3[1, 1, 0])

6


#### Slicing

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1[2:5:2]

array([2, 4])

In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a2[0:2, 1::2]

array([[1, 3],
       [5, 7]])

In [44]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [45]:
a2[1, ::3]

array([4, 7])

In [46]:
a2[0, :]

array([0, 1, 2, 3])

In [47]:
a2[:, 2]

array([ 2,  6, 10])

In [48]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [49]:
a3 = np.arange(27).reshape(3, 3, 3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [51]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [52]:
a3[0, 1, :]

array([3, 4, 5])

### Iterating

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [55]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [57]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [59]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [60]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# reshape
a1.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# Transpose
# np.transpose is equivalent to .T
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [64]:
# ravel => flattening the array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [65]:
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)
a4, a5

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [66]:
# horizontal stacking
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [67]:
# Vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [68]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
# horizontal splitting

np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [70]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
# vertical splitting
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]