### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [2]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[71, 82, 61,  6],
       [21, 90, 57, 61],
       [84, 78, 42, 11],
       [ 6, 31, 39, 93],
       [50, 59, 62, 98],
       [15, 97, 44, 32]], dtype=int32)

In [3]:
np.sort(a)[::-1]

array([99, 83, 69, 69, 63, 61, 60, 59, 53, 40, 37, 30, 15, 12,  9],
      dtype=int32)

In [4]:
np.sort(b, axis=0)  # axis=0 means column-wise sorting, axis=1 means row-wise sorting

array([[ 6, 31, 39,  6],
       [15, 59, 42, 11],
       [21, 78, 44, 32],
       [50, 82, 57, 61],
       [71, 90, 61, 93],
       [84, 97, 62, 98]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
np.append(a, 200)

array([ 37,  53,  61,  12,  63,  30,  69,  59,  69,  99,   9,  15,  83,
        60,  40, 200])

In [6]:
b

array([[71, 82, 61,  6],
       [21, 90, 57, 61],
       [84, 78, 42, 11],
       [ 6, 31, 39, 93],
       [50, 59, 62, 98],
       [15, 97, 44, 32]], dtype=int32)

In [7]:
np.append(
    b, np.random.random((b.shape[0], 1)), axis=1
)  # axis=1 means column-wise appending, adding a new column

array([[71.        , 82.        , 61.        ,  6.        ,  0.93978304],
       [21.        , 90.        , 57.        , 61.        ,  0.94833314],
       [84.        , 78.        , 42.        , 11.        ,  0.5152499 ],
       [ 6.        , 31.        , 39.        , 93.        ,  0.31033685],
       [50.        , 59.        , 62.        , 98.        ,  0.77163586],
       [15.        , 97.        , 44.        , 32.        ,  0.45146352]])

### np.concatenate

np.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c, d), axis=0)  # axis=0 means row-wise concatenation

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c, d), axis=1)  # axis=1 means column-wise concatenation

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [14]:
a.shape

(15,)

In [15]:
np.expand_dims(a, axis=0).shape  # axis=0 means adding a new row

(1, 15)

In [16]:
np.expand_dims(a, axis=1)  # axis=1 means adding a new column

array([[37],
       [53],
       [61],
       [12],
       [63],
       [30],
       [69],
       [59],
       [69],
       [99],
       [ 9],
       [15],
       [83],
       [60],
       [40]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [17]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [18]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 1,  2,  4,  6,  7,  8,  9, 12, 13]),)

In [19]:
# replace all values > 50 with 0
np.where(a > 50, 0, a)

array([37,  0,  0, 12,  0, 30,  0,  0,  0,  0,  9, 15,  0,  0, 40],
      dtype=int32)

In [20]:
np.where(a % 2 == 0, 0, a)

array([37, 53, 61,  0, 63,  0, 69, 59, 69, 99,  9, 15, 83,  0,  0],
      dtype=int32)

In [21]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [23]:
np.argmax(a)

np.int64(9)

In [24]:
b

array([[71, 82, 61,  6],
       [21, 90, 57, 61],
       [84, 78, 42, 11],
       [ 6, 31, 39, 93],
       [50, 59, 62, 98],
       [15, 97, 44, 32]], dtype=int32)

In [25]:
np.argmax(b, axis=0)  # axis=0 means column-wise maximum indices

array([2, 5, 4, 4])

In [26]:
np.argmax(b, axis=1)  # axis=1 means row-wise maximum indices

array([1, 1, 0, 3, 3, 1])

In [27]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [28]:
# np.argmin
np.argmin(a)

np.int64(10)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [29]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [30]:
np.cumsum(a)

array([ 37,  90, 151, 163, 226, 256, 325, 384, 453, 552, 561, 576, 659,
       719, 759])

In [31]:
b

array([[71, 82, 61,  6],
       [21, 90, 57, 61],
       [84, 78, 42, 11],
       [ 6, 31, 39, 93],
       [50, 59, 62, 98],
       [15, 97, 44, 32]], dtype=int32)

In [32]:
np.cumsum(b, axis=1)  # axis=1 means row-wise cumulative sum

array([[ 71, 153, 214, 220],
       [ 21, 111, 168, 229],
       [ 84, 162, 204, 215],
       [  6,  37,  76, 169],
       [ 50, 109, 171, 269],
       [ 15, 112, 156, 188]])

In [33]:
np.cumsum(b)

array([  71,  153,  214,  220,  241,  331,  388,  449,  533,  611,  653,
        664,  670,  701,  740,  833,  883,  942, 1004, 1102, 1117, 1214,
       1258, 1290])

In [34]:
# np.cumprod
np.cumprod(a)

array([                  37,                 1961,               119621,
                    1435452,             90433476,           2713004280,
               187197295320,       11044640423880,      762080189247720,
          75445938735524280,   679013448619718520, -8261542344413773816,
       -3178483859089816936, -6241590808293500000,  8590784700193722624])

In [35]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [36]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [37]:
np.percentile(a, 50)

np.float64(59.0)

In [38]:
np.median(a)

np.float64(59.0)

In [39]:
b

array([[71, 82, 61,  6],
       [21, 90, 57, 61],
       [84, 78, 42, 11],
       [ 6, 31, 39, 93],
       [50, 59, 62, 98],
       [15, 97, 44, 32]], dtype=int32)

In [40]:
np.percentile(b, 50, axis=0)  # axis=0 means column-wise percentiles

array([35.5, 80. , 50.5, 46.5])

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [41]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [42]:
np.histogram(a, bins=[0, 50, 100])

(array([6, 9]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [43]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [44]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [45]:
items = [10, 20, 30, 40, 50, 60, 70, 80, 93, 100]
print(items)
print(np.isin(a, items))
a[np.isin(a, items)]

[10, 20, 30, 40, 50, 60, 70, 80, 93, 100]
[False False False False False  True False False False False False False
 False  True  True]


array([30, 60, 40], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [46]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [47]:
np.flip(a)

array([40, 60, 83, 15,  9, 99, 69, 59, 69, 30, 63, 12, 61, 53, 37],
      dtype=int32)

In [48]:
b

array([[71, 82, 61,  6],
       [21, 90, 57, 61],
       [84, 78, 42, 11],
       [ 6, 31, 39, 93],
       [50, 59, 62, 98],
       [15, 97, 44, 32]], dtype=int32)

In [49]:
np.flip(b, axis=1)  # axis=1 means flipping columns

array([[ 6, 61, 82, 71],
       [61, 57, 90, 21],
       [11, 42, 78, 84],
       [93, 39, 31,  6],
       [98, 62, 59, 50],
       [32, 44, 97, 15]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [50]:
a

array([37, 53, 61, 12, 63, 30, 69, 59, 69, 99,  9, 15, 83, 60, 40],
      dtype=int32)

In [51]:
np.put(a, [0, 1], [110, 530])

In [52]:
a

array([110, 530,  61,  12,  63,  30,  69,  59,  69,  99,   9,  15,  83,
        60,  40], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [53]:
a

array([110, 530,  61,  12,  63,  30,  69,  59,  69,  99,   9,  15,  83,
        60,  40], dtype=int32)

In [54]:
np.delete(a, [0, 2, 4])

array([530,  12,  30,  69,  59,  69,  99,   9,  15,  83,  60,  40],
      dtype=int32)

In [55]:
a

array([110, 530,  61,  12,  63,  30,  69,  59,  69,  99,   9,  15,  83,
        60,  40], dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [56]:
m = np.array([1, 2, 3, 4, 5])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
np.intersect1d(m, n)

array([3, 4, 5])

In [58]:
np.setdiff1d(m, n)

array([1, 2])

In [59]:
np.setxor1d(m, n)

array([1, 2, 6, 7])

In [60]:
print(np.in1d(m, 1))
print(np.isin(m, 1))
m[np.in1d(m, 1)]

[ True False False False False]
[ True False False False False]


C:\Users\YASH\AppData\Local\Temp\ipykernel_19088\2593999882.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(m, 1))
C:\Users\YASH\AppData\Local\Temp\ipykernel_19088\2593999882.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m, 1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [61]:
a

array([110, 530,  61,  12,  63,  30,  69,  59,  69,  99,   9,  15,  83,
        60,  40], dtype=int32)

In [62]:
np.clip(a, a_min=25, a_max=75)

array([75, 75, 61, 25, 63, 30, 69, 59, 69, 75, 25, 25, 75, 60, 40],
      dtype=int32)

In [63]:
# 17. np.swapaxes
c = np.arange(12).reshape(3, 4)
print(c)
np.swapaxes(c, 0, 1)  # swapping rows and columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [64]:
# 18. np.random.uniform
np.random.uniform(1, 10, 5)  # generating 5 random numbers between 1 and 10

array([5.5033285 , 2.33991826, 5.66592669, 4.47933321, 8.89868348])

In [65]:
a

array([110, 530,  61,  12,  63,  30,  69,  59,  69,  99,   9,  15,  83,
        60,  40], dtype=int32)

In [66]:
# 19. np.count_nonzero
np.count_nonzero(a > 50)

10

#### [Other Numpy Functions](https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?)

#### [Other resources](https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5)


In [67]:
# 21. np.tile
np.tile(a, 3)  # repeating the array 3 times

array([110, 530,  61,  12,  63,  30,  69,  59,  69,  99,   9,  15,  83,
        60,  40, 110, 530,  61,  12,  63,  30,  69,  59,  69,  99,   9,
        15,  83,  60,  40, 110, 530,  61,  12,  63,  30,  69,  59,  69,
        99,   9,  15,  83,  60,  40], dtype=int32)

In [68]:
# 22. np.repeat
np.repeat(a, 2)  # repeating each element twice

array([110, 110, 530, 530,  61,  61,  12,  12,  63,  63,  30,  30,  69,
        69,  59,  59,  69,  69,  99,  99,   9,   9,  15,  15,  83,  83,
        60,  60,  40,  40], dtype=int32)

In [69]:
# 25. np.allclose and equals
a1 = np.array([1.0, 2.0, 3.0])
a2 = np.array([1.0, 2.0, 3.0000001])

print(np.allclose(a1, a2))
print(np.array_equal(a1, a2))

True
False
