**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
# Filling the numpy array with NaN values
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
a, b = map(int, input("Enter two numbers: ").split())
x = np.random.random((a, b))
print(x.shape)
print(x)
print(x.mean())

(2, 7)
[[0.14420154 0.4547052  0.26755214 0.92043755 0.97858184 0.68725168
  0.04338398]
 [0.75341377 0.28313583 0.34250374 0.39171346 0.18308334 0.42397829
  0.27860811]]
0.43946789062282543


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [4]:
def borderArray(a, b):
    x = np.ones((a, b))
    x[1:-1:, 1:-1:] = 0  # Except the border, changing all other elements to 0
    return x


borderArray(4, 5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [5]:
np.linspace(0, 1, 12)[1:-1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [6]:
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

# Identy matrix of size 3-- 3X3
a = np.eye(3)

# Identy matrix of size 4-- 4X4
b = np.identity(4)

# eye and identity are same.
print(a)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [7]:
z = np.zeros((5, 5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [8]:
a = np.random.randint(1, 100, (10, 2))
p = np.array([2, 3])
dis = np.sqrt(np.sum((a - p) ** 2, axis=1)).astype(int)
print(a)
print(p)
print(dis)

[[85 85]
 [ 9 27]
 [21 49]
 [36 26]
 [38 59]
 [58 97]
 [ 5 14]
 [ 4 75]
 [71  1]
 [58 27]]
[2 3]
[116  25  49  41  66 109  11  72  69  60]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [9]:
a = np.arange(6 * 7 * 8).reshape(6, 7, 8)
# print(a)
idx = np.unravel_index(100, (6, 7, 8))
print(idx)  # (1, 5, 4)
print(a[idx])  # 100

(np.int64(1), np.int64(5), np.int64(4))
100


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [10]:
a = input().strip().split()
np.array(a[::-1], dtype=np.float32)

array([-10.,  -8.,   4.,   3.,   2.,   1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [11]:
a = np.array([])
a = np.array([1, 2])
a = np.zeros((2, 3))
a.size

6

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=1}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [12]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr) / s


softmax(
    np.array(
        [86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318]
    )
)

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [13]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)


a = np.arange(10).reshape(2, -1)
print("a=", a)

b = np.repeat(1, 10).reshape(
    2, -1
)  # reshape(2,-1) means 2 rows and as many columns as required to accommodate all elements of the array
print("b=", b)

print(vertical_stack(a, b))

c = np.random.random((2, 5))
print("c=", c)

vertical_stack(a, b, c)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.28800473 0.76917377 0.70712093 0.43026078 0.73046908]
 [0.73843677 0.58734961 0.71346108 0.59299806 0.44255253]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.28800473, 0.76917377, 0.70712093, 0.43026078, 0.73046908],
       [0.73843677, 0.58734961, 0.71346108, 0.59299806, 0.44255253]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [14]:
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError

    total_days_of_month = {
        "01": 31,
        "02": 28,
        "03": 31,
        "04": 30,
        "05": 31,
        "06": 30,
        "07": 31,
        "08": 31,
        "09": 30,
        "10": 31,
        "11": 30,
        "12": 31,
    }

    end = end.split("-")
    end_last = int(end[-1]) + 1

    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f"0{days_diff}" if days_diff < 10 else f"{days_diff}"
        next_month = int(end[-2]) + 1
        end[-2] = f"0{next_month}" if next_month < 10 else f"{next_month}"
    else:
        end[-1] = f"0{end_last}" if end_last < 10 else f"{end_last}"

    end = "-".join(end)
    return np.arange(
        start, end, dtype="datetime64[D]"
    )  # Use arange() to generate all dates between start and end


date_array(start="2020-11-25", end="2020-11-30")

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

### `Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
x = np.random.random((5, 4))
x - x.mean(
    axis=1, keepdims=True
)  # keepdims=True keeps the dimensions of the original array intact

array([[ 0.14163795,  0.12936144, -0.40514461,  0.13414523],
       [-0.04685202,  0.22730445, -0.3740046 ,  0.19355217],
       [ 0.20148906,  0.1012612 , -0.01406541, -0.28868485],
       [-0.06626808,  0.24465443, -0.41894331,  0.24055697],
       [ 0.27456453, -0.22144429, -0.05427736,  0.00115712]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [16]:
a = np.arange(9).reshape(3, 3)
print(a)
print(a[:, [0, 2, 1]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


### `Q-16:` Replace odd elements in arrays with -1.

In [17]:
a = np.arange(10)
a[a % 2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [18]:
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

a[b > a] = b[a < b]
a

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [19]:
# Given
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8, 5)
arr1

array([[3199, 2238, 4614, 5671, 5108],
       [6595, 2729, 3438, 5299,  343],
       [5881, 1584, 3376, 5220, 3638],
       [6286, 6518, 3814, 4327, 1148],
       [ 461, 7279, 3864, 4705, 1360],
       [1713, 9681, 8244, 7699, 1800],
       [7894, 3879, 7471,  499, 6307],
       [7323,   29, 4973, 9203, 9632]], dtype=int32)

In [20]:
arr1[:, ::2]

array([[3199, 4614, 5108],
       [6595, 3438,  343],
       [5881, 3376, 3638],
       [6286, 3814, 1148],
       [ 461, 3864, 1360],
       [1713, 8244, 1800],
       [7894, 7471, 6307],
       [7323, 4973, 9632]], dtype=int32)

In [21]:
(arr1 - arr1.min()) / (arr1.max() - arr1.min())

array([[0.32842934, 0.22886448, 0.47503108, 0.58454206, 0.52621218],
       [0.68027352, 0.27973477, 0.35319105, 0.54600083, 0.03253212],
       [0.60629921, 0.16110651, 0.34676751, 0.537816  , 0.37391214],
       [0.64825943, 0.6722959 , 0.39214671, 0.44529631, 0.11593452],
       [0.04475756, 0.75113966, 0.39732698, 0.48445918, 0.13789888],
       [0.17447161, 1.        , 0.85111894, 0.79465396, 0.18348529],
       [0.81485702, 0.39888106, 0.77103191, 0.04869457, 0.65043514],
       [0.7556983 , 0.        , 0.51222545, 0.95047659, 0.99492333]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
def nthmax(arr, n):
    if n > len(arr):
        raise IndexError("n is way out of limit")
    arr.sort()
    return arr[-n]


n = 3
nthmax(np.array([12, 34, 40, 7, 1, 0]), n)

np.int64(12)

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [23]:
a = np.array([1, 2, 3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])